export interface AppTheme {
  id: string;
  name: string;
  mono: string;
  type: 'dark' | 'light';
  css: Record<string, string>;
}

export const THEMES: AppTheme[] = [
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    mono: 'tokyo-night',
    type: 'dark',
    css: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      card: '#16161e',
      'card-foreground': '#c0caf5',
      primary: '#7aa2f7',
      'primary-foreground': '#1a1b26',
      secondary: '#1f2335',
      'secondary-foreground': '#a9b1d6',
      muted: '#1f2335',
      'muted-foreground': '#565f89',
      accent: '#bb9af7',
      'accent-foreground': '#1a1b26',
      destructive: '#f7768e',
      'destructive-foreground': '#1a1b26',
      border: '#3b4261',
      input: '#3b4261',
      ring: '#7aa2f7',
      success: '#9ece6a',
      warning: '#e0af68',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    mono: 'dracula',
    type: 'dark',
    css: {
      background: '#282a36',
      foreground: '#f8f8f2',
      card: '#21222c',
      'card-foreground': '#f8f8f2',
      primary: '#bd93f9',
      'primary-foreground': '#282a36',
      secondary: '#44475a',
      'secondary-foreground': '#f8f8f2',
      muted: '#44475a',
      'muted-foreground': '#6272a4',
      accent: '#ff79c6',
      'accent-foreground': '#282a36',
      destructive: '#ff5555',
      'destructive-foreground': '#f8f8f2',
      border: '#44475a',
      input: '#44475a',
      ring: '#bd93f9',
      success: '#50fa7b',
      warning: '#f1fa8c',
    },
  },
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    mono: 'one-dark-pro',
    type: 'dark',
    css: {
      background: '#282c34',
      foreground: '#abb2bf',
      card: '#21252b',
      'card-foreground': '#abb2bf',
      primary: '#61afef',
      'primary-foreground': '#282c34',
      secondary: '#3e4451',
      'secondary-foreground': '#abb2bf',
      muted: '#3e4451',
      'muted-foreground': '#5c6370',
      accent: '#c678dd',
      'accent-foreground': '#282c34',
      destructive: '#e06c75',
      'destructive-foreground': '#abb2bf',
      border: '#3e4451',
      input: '#3e4451',
      ring: '#61afef',
      success: '#98c379',
      warning: '#e5c07b',
    },
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin Mocha',
    mono: 'catppuccin-mocha',
    type: 'dark',
    css: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      card: '#181825',
      'card-foreground': '#cdd6f4',
      primary: '#89b4fa',
      'primary-foreground': '#1e1e2e',
      secondary: '#313244',
      'secondary-foreground': '#cdd6f4',
      muted: '#313244',
      'muted-foreground': '#6c7086',
      accent: '#f5c2e7',
      'accent-foreground': '#1e1e2e',
      destructive: '#f38ba8',
      'destructive-foreground': '#1e1e2e',
      border: '#45475a',
      input: '#45475a',
      ring: '#89b4fa',
      success: '#a6e3a1',
      warning: '#f9e2af',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    mono: 'nord',
    type: 'dark',
    css: {
      background: '#2e3440',
      foreground: '#eceff4',
      card: '#3b4252',
      'card-foreground': '#eceff4',
      primary: '#81a1c1',
      'primary-foreground': '#2e3440',
      secondary: '#3b4252',
      'secondary-foreground': '#eceff4',
      muted: '#3b4252',
      'muted-foreground': '#4c566a',
      accent: '#88c0d0',
      'accent-foreground': '#2e3440',
      destructive: '#bf616a',
      'destructive-foreground': '#eceff4',
      border: '#4c566a',
      input: '#4c566a',
      ring: '#81a1c1',
      success: '#a3be8c',
      warning: '#ebcb8b',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    mono: 'monokai',
    type: 'dark',
    css: {
      background: '#272822',
      foreground: '#f8f8f2',
      card: '#1e1f1c',
      'card-foreground': '#f8f8f2',
      primary: '#66d9ef',
      'primary-foreground': '#272822',
      secondary: '#3e3d32',
      'secondary-foreground': '#f8f8f2',
      muted: '#3e3d32',
      'muted-foreground': '#75715e',
      accent: '#ae81ff',
      'accent-foreground': '#272822',
      destructive: '#f92672',
      'destructive-foreground': '#f8f8f2',
      border: '#49483e',
      input: '#49483e',
      ring: '#66d9ef',
      success: '#a6e22e',
      warning: '#e6db74',
    },
  },
  {
    id: 'light',
    name: 'Light',
    mono: 'vs',
    type: 'light',
    css: {
      background: '#ffffff',
      foreground: '#222222',
      card: '#ffffff',
      'card-foreground': '#222222',
      primary: '#222222',
      'primary-foreground': '#ffffff',
      secondary: '#f5f5f5',
      'secondary-foreground': '#222222',
      muted: '#f5f5f5',
      'muted-foreground': '#717171',
      accent: '#0066cc',
      'accent-foreground': '#ffffff',
      destructive: '#d32f2f',
      'destructive-foreground': '#ffffff',
      border: '#e0e0e0',
      input: '#e0e0e0',
      ring: '#222222',
      success: '#2e7d32',
      warning: '#f57c00',
    },
  },
];

export const DEFAULT_THEME_ID = 'tokyo-night';

export function getTheme(id: string): AppTheme {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}
